import HeroBanner from "@/components/HeroBanner";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>YYC Devs | Find the talent you need, locally.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner />
    </>
  );
}
