import ProfileCard from "@/components/ProfileCard/ProfileCard";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>YYC Devs | Find the talent that you need, locally.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello
      <ProfileCard
        name={"Forest Park"}
        title={"Full Stack Developer"}
        description={"I Like cat videos"}
        avatarImgSrc={
          "https://www.thecountrycook.net/wp-content/uploads/2021/02/thumbnail-Southern-Fried-Chicken-scaled.jpg"
        }
      />
    </>
  );
}
